name: Deploy to Dev

on:
  push:
    branches: [ dev ]

jobs:
  deploy-dev:
    name: Deployment Dev
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGION : us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init ✅
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file="dev.tfvars"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var-file="dev.tfvars" -var="create_role=false" -input=false -no-color -parallelism=10

      - name: Deploy Lambda
        run: bash deploy/deploy_lambda.sh dev

      - name: Deploy Lex Bot from ZIP (if available)
        shell: bash
        run: python deploy/import_or_create_lex_bot.py --bot bot1 --env dev

      - name: Deploy Connect Flow
        run: python deploy/deploy_connect.py --env dev

      - name: Upload failure logs
        if: failure()
        run: echo "Check Lambda or Lex logs in CloudWatch if errors occurred."
