name: Import Lex Bot from ZIP

on:
  push:
    paths:
      - 'lex/bot1/exported/dev/*.zip'

jobs:
  import-lex-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Import Lex bot from ZIP
        id: lex-import
        run: |
          echo "🔍 Looking for Lex ZIP..."
          FILE=$(find lex/bot1/exported/dev -name '*.zip' | head -n 1)

          if [ -z "$FILE" ]; then
            echo "❌ No zip file found to import"
            exit 1
          fi

          echo "📦 Importing bot from: $FILE"
          IMPORT_ID=$(aws lexv2-models start-import \
            --region us-east-1 \
            --resource-specification bot=@"$FILE" \
            --merge-strategy Overwrite \
            --query importId \
            --output text)

          echo "🆔 Import ID: $IMPORT_ID"
          echo "import_id=$IMPORT_ID" >> "$GITHUB_OUTPUT"

      - name: Wait for Lex import to complete
        run: |
          IMPORT_ID="${{ steps.lex-import.outputs.import_id }}"
          echo "⏳ Waiting for import to complete for ID: $IMPORT_ID"

          STATUS="InProgress"
          ATTEMPTS=0
          MAX_ATTEMPTS=20

          while [[ "$STATUS" == "InProgress" || "$STATUS" == "Waiting" ]]; do
            STATUS=$(aws lexv2-models describe-import \
              --import-id "$IMPORT_ID" \
              --region us-east-1 \
              --query 'importStatus' \
              --output text)

            echo "🕒 Attempt $ATTEMPTS → Status: $STATUS"

            if [[ "$STATUS" == "Completed" ]]; then
              echo "✅ Import completed successfully!"
              exit 0
            elif [[ "$STATUS" == "Failed" ]]; then
              echo "❌ Import failed."
              aws lexv2-models describe-import \
                --import-id "$IMPORT_ID" \
                --region us-east-1 \
                --output json
              exit 1
            fi

            sleep 10
            ((ATTEMPTS++))

            if [[ $ATTEMPTS -ge $MAX_ATTEMPTS ]]; then
              echo "❌ Timed out waiting for import to complete."
              exit 1
            fi
          done
